{
  "at" => "Austria",
  "be" => "Belgium",
  "bg" => "Bulgaria",
  "cy" => "Cyprus",
  "cz" => "Czech Republic",
  "de" => "Germany",
  "dk" => "Denmark",
  "ee" => "Estonia",
  "es" => "Spain",
  "fi" => "Finland",
  "fr" => "France",
  "gb" => "United Kingdom",
  "gi" => "Gibraltar",
  "gr" => "Greece",
  "hu" => "Hungary",
  "ie" => "Ireland",
  "it" => "Italy",
  "lt" => "Lithuania",
  "lu" => "Luxembourg",
  "lv" => "Latvia",
  "mt" => "Malta",
  "nl" => "Netherlands",
  "pl" => "Poland",
  "pt" => "Portugal",
  "ro" => "Romania",
  "se" => "Sweden",
  "si" => "Slovenia",
  "sk" => "Slovakia",
}.each do |code, name|
  Country.create!(:code => code, :name => name)
end

{
  "bg" => "Bulgarian",
  "cs" => "Czech",
  "da" => "Danish",
  "nl" => "Dutch",
  "en" => "English",
  "et" => "Estonian",
  "fi" => "Finnish",
  "fr" => "French",
  "de" => "German",
  "el" => "Greek",
  "hu" => "Hungarian",
  "ga" => "Irish",
  "it" => "Italian",
  "lv" => "Latvian",
  "lt" => "Lithuanian",
  "mt" => "Maltese",
  "pl" => "Polish",
  "pt" => "Portuguese",
  "ro" => "Romanian",
  "sk" => "Slovak",
  "sl" => "Slovene",
  "es" => "Spanish",
  "sv" => "Swedish",
}.each do |code, name|
  Language.create!(:code => code, :name => name)
end
